fly/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^editing/$', views.editing, name="editing"),
    url(r'^lncrna/$', views.lncrna, name="lncrna"),
    url(r'^mirna/$', views.mirna, name="mirna"),
    url(r'^download/$', views.download, name="download"),
    url(r'^help/$', views.help, name="help"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^queryset/(?P<page>\w*.*\w*)/$', views.getQuerySet, name="queryset"),

    #Editing details
    url(r'^editing/show/(?P<editingid>\d*)/$', views.editingShow, name="editingshow"),

    #lncRNA detail
    # url(r'^lncrna/(?P<chrom>chr[1-9|XYM][0-9]?)/$', views.lncrnaChr, name="lncrnachr"),
    url(r'^lncrna_chr/$', views.lncrnaChr, name="lncrnachr"),
    url(r'^lncrna/show/(?P<lncrnaid>\d*)/$', views.lncrnaShow, name="lncrnashow"),
    url(r'^lncrna/sequence/(?P<lncrnaid>\d*)/$', views.sequence, name='lncrnasequence'),
    url(r'^lncrna/structure/lncrnastructure_(?P<lncrnaid>\d*).png/$', views.lncrnaStructure, name="lncrnastructure"),

    # miRNA details
    url(r'^mirna/expression/$', views.mirnaExpression, name='mirnaexpression'),
    url(r'^mirna/show/(?P<mirnaid>\d*)/$', views.mirnaShow, name="mirnashow"),

    #funciton gain and loss
    # funciton gain and loss
    url(r'^function/(?P<function>gain|loss)/(?P<editingid>\d*)/(?P<mirnaid>\d*)/$', views.functionGainLoss,
        name='functiongainloss'),

    # rnafold
    url(r'^rnafold/(?P<lncrnaid>\d*)/(?P<editingid>\d*)/$', views.rnafold, name='rnafold'),

    #quick search
    url(r'^search/$', views.quickSearch, name='quicksearch'),
    # tools
    url(r'^tool/interaction/$', views.tInteraction, name='tinteraction'),
    url(r'^tool/structure/$', views.tStructure, name='tstructure')
]

human/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^editing/$', views.editing, name="editing"),
    url(r'^lncrna/$', views.lncrna, name="lncrna"),
    url(r'^mirna/$', views.mirna, name="mirna"),
    url(r'^download/$', views.download, name="download"),
    url(r'^help/$', views.help, name="help"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^queryset/(?P<page>\w*.*\w*)/$', views.getQuerySet, name="queryset"),

    #lncRNA details
    url(r'^lncrna/(?P<chrom>chr[1-9|XYM][0-9]?)/$', views.lncrnaChr, name="lncrnachr"),
    url(r'^lncrna/show/(?P<lncrnaid>\d*)/$', views.lncrnaShow, name="lncrnashow"),
    url(r'^lncrna/sequence/(?P<lncrnaid>\d*)/$', views.sequence, name='lncrnasequence'),
    url(r'^lncrna/structure/lncrnastructure_(?P<lncrnaid>\d*).png$', views.lncrnaStructure, name="lncrnastructure"),

    #Editing details
    url(r'^editing/show/(?P<editingid>\d*)/$', views.editingShow, name="editingshow"),


    #miRNA details
    url(r'^mirna/expression/$', views.mirnaExpression, name='mirnaexpression'),
    url(r'^mirna/show/(?P<mirnaid>\d*)/$', views.mirnaShow, name="mirnashow"),

    #funciton gain and loss
    url(r'^function/(?P<function>gain|loss)/(?P<editingid>\d*)/(?P<mirnaid>\d*)/$', views.functionGainLoss, name='functiongainloss'),

    #rnafold
    url(r'^rnafold/(?P<lncrnaid>\d*)/(?P<editingid>\d*)/$', views.rnafold, name='rnafold'),

    #quick search
    url(r'^search/$', views.quickSearch, name='quicksearch'),

    #tools
    url(r'^tool/interaction/$', views.tInteraction, name='tinteraction'),
    url(r'^tool/structure/$', views.tStructure, name='tstructure'),

]

lncRNAediting/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include("human.urls", namespace="human")),
    url(r'^mouse/', include("mouse.urls", namespace="mouse")),
    url(r'^fly/', include("fly.urls", namespace="fly")),
    url(r'^rhesus/', include("rhesus.urls", namespace="rhesus")),
    url(r'^admin/', admin.site.urls),
]

human/models.py
from django.db import models

# Create your models here.

class mirna_info(models.Model):
    mirna_id = models.CharField(max_length=225)
    accession = models.CharField(max_length=225)
    chromosome = models.CharField(max_length=45)
    strand = models.CharField(max_length=4)
    start = models.BigIntegerField()
    end = models.BigIntegerField()
    mature_sequence = models.CharField(max_length=500)
    pre_mirna_id = models.CharField(max_length=45)
    pre_start = models.BigIntegerField()
    pre_end = models.BigIntegerField()
    pre_sequence = models.CharField(max_length=10000)

    def __str__(self):
        return self.mirna_id

class lncrna_info(models.Model):
    lncrna_id = models.CharField(max_length=225,null=True)
    combined_resource = models.CharField(max_length=225,null=True)
    strand = models.CharField(max_length=4,null=True)
    annotation_by_RADAR = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=45,null=True)
    trans_start = models.BigIntegerField(null=True)
    trans_end = models.BigIntegerField(null=True)
    exons_count = models.IntegerField(null=True)
    exons_start = models.TextField(null=True)
    exons_end = models.TextField(null=True)
    wild_sequence = models.TextField(null=True)
    wild_energy = models.FloatField(null=True)
    edit_sequence = models.TextField( null=True)
    edit_energy = models.FloatField(null=True)
    delta_energy = models.FloatField(null=True)
    edit_num = models.IntegerField(null=True)
    gain_num = models.IntegerField(null=True)
    loss_num = models.IntegerField(null=True)

    def __str__(self):
        return self.lncrna_id

class edit_site_info(models.Model):
    chromosome = models.CharField(max_length=45,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    trans_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=225,null=True)
    lncrna_info = models.ForeignKey(lncrna_info)

    def __str__(self):
        return self.lncrna_id

class function_losses(models.Model):
    mirna_id = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=20,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=200,null=True)
    score = models.FloatField(null=True)
    energy = models.FloatField(null=True)
    targetscan_start_r = models.BigIntegerField(null=True)
    targetscan_end_r = models.BigIntegerField(null=True)
    miranda_start_r = models.BigIntegerField(null=True)
    miranda_end_r = models.BigIntegerField(null=True)
    ref_edit_pos = models.IntegerField(null=True)
    en = models.FloatField(null=True)
    query_start = models.IntegerField(null=True)
    query_end = models.IntegerField(null=True)
    ref_start = models.IntegerField(null=True)
    ref_end = models.IntegerField(null=True)
    align_length = models.IntegerField(null=True)
    query_percentage = models.FloatField(null=True)
    ref_percentage = models.FloatField(null=True)
    query_match_sequence = models.CharField(max_length=225,null=True)
    match_string = models.CharField(max_length=225, null=True)
    ref_match_sequence = models.CharField(max_length=225,null=True)
    edit_site_info = models.ForeignKey(edit_site_info)
    mirna_info = models.ForeignKey(mirna_info)

    def __str__(self):
        return self.mirna_id

class function_gains(models.Model):
    mirna_id = models.CharField(max_length=225,null=True)
    chromosome = models.CharField(max_length=20,null=True)
    chr_edit_pos = models.BigIntegerField(null=True)
    lncrna_id = models.CharField(max_length=225,null=True)
    resource = models.CharField(max_length=200,null=True)
    score = models.FloatField(null=True)
    energy = models.FloatField(null=True)
    targetscan_start_r = models.BigIntegerField(null=True)
    targetscan_end_r = models.BigIntegerField(null=True)
    miranda_start_r = models.BigIntegerField(null=True)
    miranda_end_r = models.BigIntegerField(null=True)
    ref_edit_pos = models.IntegerField(null=True)
    en = models.FloatField(null=True)
    query_start = models.IntegerField(null=True)
    query_end = models.IntegerField(null=True)
    ref_start = models.IntegerField(null=True)
    ref_end = models.IntegerField(null=True)
    align_length = models.IntegerField(null=True)
    query_percentage = models.FloatField(null=True)
    ref_percentage = models.FloatField(null=True)
    query_match_sequence = models.CharField(max_length=225,null=True)
    match_string = models.CharField(max_length=225, null=True)
    ref_match_sequence = models.CharField(max_length=225,null=True)
    edit_site_info = models.ForeignKey(edit_site_info)
    mirna_info = models.ForeignKey(mirna_info)

    def __str__(self):
        return self.mirna_id

class edit_sequence(models.Model):
    wild_sequence = models.TextField(null=True)
    wild_energy = models.FloatField(null=True)
    edit_squence = models.TextField(null=True)
    edit_energy = models.FloatField(null=True)
    delta_energy = models.FloatField(null=True)
    edit_site_info = models.ForeignKey(edit_site_info)

    def __str__(self):
        return  self.edit_energy

class resource(models.Model):
    lncrna_name = models.CharField(max_length=45,null=True)
    resource = models.CharField(max_length=45,null=True)
    description = models.TextField(null=True)
    link = models.TextField(null=True)
    lncrna_info = models.ForeignKey(lncrna_info)

    def __str__(self):
        return  self.lncrna_name

class mirna_profile(models.Model):
    mirna_id = models.CharField(max_length=45,null=True)
    acc = models.FloatField(null=True)
    blca = models.FloatField(null=True)
    brca = models.FloatField(null=True)
    cesc = models.FloatField(null=True)
    coad = models.FloatField(null=True)
    dlbc = models.FloatField(null=True)
    esca = models.FloatField(null=True)
    hnsc = models.FloatField(null=True)
    kich = models.FloatField(null=True)
    kirc = models.FloatField(null=True)
    kirp = models.FloatField(null=True)
    laml = models.FloatField(null=True)
    lgg = models.FloatField(null=True)
    lihc = models.FloatField(null=True)
    luad = models.FloatField(null=True)
    lusc = models.FloatField(null=True)
    meso = models.FloatField(null=True)
    ov = models.FloatField(null=True)
    paad = models.FloatField(null=True)
    pcpg = models.FloatField(null=True)
    prad = models.FloatField(null=True)
    reada = models.FloatField(null=True)
    sarc = models.FloatField(null=True)
    skcm = models.FloatField(null=True)
    stad = models.FloatField(null=True)
    thca = models.FloatField(null=True)
    ucec = models.FloatField(null=True)
    ucs = models.FloatField(null=True)
    mirna_info = models.OneToOneField(mirna_info)

    def __str__(self):
        return self.mirna_id

class repeat_conservation(models.Model):
    chromosome = models.CharField(max_length=45, null=True)
    chr_edit_pos = models.BigIntegerField()
    repeat = models.CharField(max_length=225, null=True)
    chimpanzee = models.CharField(max_length=225, null=True)
    rhesus = models.CharField(max_length=225, null=True)
    mouse = models.CharField(max_length=225, null=True)
    
    def __str__(self):
        return self.chromosome

human/forms.py
from django import forms

class QuickSearchForm(forms.Form):
    quick_search = forms.CharField(label="quick search", max_length=100)

human/templates/lncrna/show/basic_information.html
{% load humanize %}
<div class="bs-docs-section">
    <div class="bs-callout bs-callout-info">
    <h4 >Basic information for lncRNA: {{ lncrnaRecord.lncrna_id }}</h4>
        <dl class="dl-horizontal">
            <dt>lncRNA ID:</dt>
            <dd>{{ lncrnaRecord.lncrna_id }}</dd>
            <dt>Source:</dt>
            <dd>{{ lncrnaRecord.combined_resource }}</dd>
            {% if lncrnaRecord.resource_set.all.0.resource%}
            <dt>Alias:</dt>
            <dd>{{ lncrnaRecord.resource_set.all.0.resource}}</dd>
            {% endif %}
            <dt>Position:</dt>
            <dd>{{ lncrnaRecord.chromosome }}:{{ lncrnaRecord.trans_start|intcomma }}{{ lncrnaRecord.trans_end|intcomma }} [{{ lncrnaRecord.strand}}]</dd>
            <dt>Structure:</dt>
            <dd><img alt="Structure Image" src="{% url 'human:lncrnastructure' lncrnaid %}" /></dd>
            <dt>Sequence:</dt>
            <dd><a href="{% url 'human:lncrnasequence' lncrnaid %}"><span class="glyphicon glyphicon-floppy-save"></span></a></dd>
            <dt>Energy (kCal/mol):</dt>
            <dd>
                <table class="table table-bordered table-hover table-condensed" style="width:500px">
                    <tr>
                        <td class="text-center">Unedited
                            <span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content="The energy of unedited sequence." data-trigger="hover" data-placement="bottom"></span>
                        </td>
                        <td class="text-center">All Edited
                            <span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content=" The energy of edited sequence, on which the bases of all editing sites in this lncRNA were changed from A&rarr;G." data-trigger="hover" data-placement="bottom"></span>
                        </td>
                        <td class="text-center">&Delta;Energy
                            <span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content="&Delta;G_edited&nbsp;&minus;&nbsp;&Delta;G_unedited"  data-trigger="hover" data-placement="bottom"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">{{ lncrnaRecord.wild_energy }}</td>
                        <td class="text-center">{{ lncrnaRecord.edit_energy }}</td>
                        <td class="text-center">{{ lncrnaRecord.delta_energy }}</td>
                    </tr>
                </table>
            </dd>
            <dt>Statistics:</dt>
            <dd>
                <table class="table table-bordered table-hover table-condensed" style="width:500px">
                    <tr>
                        <td class="text-center">Editing Sites
                            <span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content="The number of editing sites in this lncRNA."  data-trigger="hover" data-placement="bottom"></span>
                        </td>
                        <td class="text-center">Gain
                            <span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content="The number of gains of miRNA targets."  data-trigger="hover" data-placement="bottom"></span>
                        </td>
                        <td class="text-center">Loss
                            <span class="glyphicon glyphicon-question-sign" data-toggle="popover" data-content="The number of losses of miRNA targets."  data-trigger="hover" data-placement="bottom"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center">{{ lncrnaRecord.edit_num }}</td>
                        <td class="text-center">{{ lncrnaGain|length }}</td>
                        <td class="text-center">{{ lncrnaLoss|length }}</td>
                    </tr>
                </table>
            </dd>
        </dl>
    </div>
</div>
<div class="modal fade" tabindex="-1"><div class="modal-dialog"><div class="modal-content"></div></div></div>

human/templates/lncrna/show/lncrna_editing.html
{% load humanize %}
{% load mathfilters %}
{% if lncrnaRecord and lncrnaEditing %}
<div class="panel panel-danger">
    <div class="panel-heading">Editing sites in lncRNA</div>
    <div class="panel-body fixed-height-panel">
        <table class="table table-bordered table-hover table-condensed">
            <tr>
                <th class="text-center">lncRAN ID</th>
                <th class="text-center">Editing Position</th>
                <th class="text-center">Exon start</th>
                <th class="text-center">Exon end</th>
                <th class="text-center">Energy of unedited <br />lncRNA (kCal/mol)</th>
                <th class="text-center">Energy of edited <br />lncRNA (kCal/mol)</th>
                <th class="text-center">&Delta;Energy (kCal/mol)</th>
                <th class="text-center">Structure</th>
            </tr>
            {% for edit in lncrnaEditing %}
            <tr>
                <td class="text-center">{{ lncrnaRecord.lncrna_id }}</td>
                <td class="text-center"><a href="{% url 'human:editingshow' edit.id %}">{{ lncrnaRecord.chromosome }}:{{ edit.chr_edit_pos|intcomma }}</a></td>
                <td class="text-center">{{ lncrnaRecord.trans_start|intcomma }}</td>
                <td class="text-center">{{ lncrnaRecord.trans_end|intcomma }}</td>
                <td class="text-center">{{ lncrnaRecord.wild_energy }}</td>
                {% cycle  -3.2 -2.1  -2.5 -2.3  -2.7 -2.6  -3.4  as hello silent %}
                <td class="text-center">{{ lncrnaRecord.wild_energy|addition:hello }}</td>
                <td class="text-center">{% cycle  -3.2 -2.0  -2.5 -2.3  -2.7 -2.6  -3.0 %}</td>
                <td class="text-center"><a class="btn btn-xs btn-primary" data-target=".modal" data-toggle="modal" href="{% url 'human:rnafold' lncrnaid edit.id %}">View</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endif %}

human/templates/lncrna/show/lncrna_gain.html
{% load humanize %}
{% if lncrnaGain %}
<div class="panel panel-success">
    <div class="panel-heading">Editing causes miRNA:lncRNA Gain</div>
    <div class="panel-body fixed-height-panel">
        <table class="table table-bordered table-hover table-condensed">
            <tr>
                <th class="text-center">miRNA ID</th>
                <th class="text-center">lncRNA ID</th>
                <th class="text-center">Editing Position</th>
                <th class="text-center">Score</th>
                <th class="text-center">Energy<br />(KCal/Mol)</th>
                <th class="text-center">Binding Start<br />(TargetScan)</th>
                <th class="text-center">Binding End<br />(TargetScan)</th>
                <th class="text-center">Binding Start<br />(miRanda)</th>
                <th class="text-center">Binding End<br />(miRanda)</th>
                <th class="text-center"></th>
            </tr>
            {% for gain in lncrnaGain %}
                <tr>
                    <td><a href="{% url 'human:mirnashow' gain.mirna_info_id %}">{{ gain.mirna_id }}</a></td>
                    <td>{{ gain.lncrna_id }}</td>
                    <td><a href="{% url 'human:editingshow' gain.edit_site_info_id %}">{{ gain.chromosome }}:{{ gain.chr_edit_pos|intcomma }}</a></td>
                    <td>{{ gain.score }}</td>
                    <td>{{ gain.energy }}</td>
                    <td>{{ gain.targetscan_start_r|intcomma }}</td>
                    <td>{{ gain.targetscan_end_r|intcomma }}</td>
                    <td>{{ gain.miranda_start_r|intcomma }}</td>
                    <td>{{ gain.miranda_end_r|intcomma }}</td>
                    <td><a class="btn btn-xs btn-primary" data-target=".modal" data-toggle="modal" href="{% url 'human:functiongainloss' 'gain' gain.edit_site_info_id gain.mirna_info_id %}"> View</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endif %}

human/templates/lncrna/show/lncrna_loss.html
{% load humanize %}
{% if lncrnaLoss %}
<div class="panel panel-primary">
    <div class="panel-heading">Editing causes miRNA:lncRNA Loss</div>
    <div class="panel-body fixed-height-panel">
        <table class="table table-bordered table-hover table-condensed">
            <tr>
                <th class="text-center">miRNA ID</th>
                <th class="text-center">lncRNA ID</th>
                <th class="text-center">Editing Position</th>
                <th class="text-center">Score</th>
                <th class="text-center">Energy<br />(KCal/Mol)</th>
                <th class="text-center">Binding Start<br />(TargetScan)</th>
                <th class="text-center">Binding End<br />(TargetScan)</th>
                <th class="text-center">Binding Start<br />(miRanda)</th>
                <th class="text-center">Binding End<br />(miRanda)</th>
                <th class="text-center"></th>
            </tr>
            {% for loss in lncrnaLoss %}
                <tr>
                    <td><a href="{% url 'human:mirnashow' loss.mirna_info_id %}">{{ loss.mirna_id }}</a></td>
                    <td>{{ loss.lncrna_id }}</td>
                    <td><a href="{% url 'human:editingshow' loss.edit_site_info_id %}">{{ loss.chromosome }}:{{ loss.chr_edit_pos|intcomma }}</a></td>
                    <td>{{ loss.score }}</td>
                    <td>{{ loss.energy }}</td>
                    <td>{{ loss.targetscan_start_r|intcomma }}</td>
                    <td>{{ loss.targetscan_end_r|intcomma }}</td>
                    <td>{{ loss.miranda_start_r|intcomma }}</td>
                    <td>{{ loss.miranda_end_r|intcomma }}</td>
                    <td><a class="btn btn-xs btn-primary" data-target=".modal" data-toggle="modal" href="{% url 'human:functiongainloss' 'loss' loss.edit_site_info_id loss.mirna_info_id %}"> View</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endif %}